# Setup
title: luca@sysadmin
url: https://lborruto.github.io
paginate: 1
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
ga_analytics: G-VVVLL6T57Z

# Specify the author for blog posts
author:
  name: Luca Borruto
  url: https://luca-borruto.com
  email: luca.borruto@gmail.com

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Projects
    url: /projects
  - title: Contact
    url: /contact